apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-go-web-app
  labels:
    app: {{ .Release.Name }}-go-web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-go-web-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-go-web-app
    spec:
      containers:
        - name: go-web-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.env.APP_VERSION }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}